save_dir: cjf_results/incloud
# save_dir: cjf_results/InCloud_MinkLoc3D_2step
debug: false
data: 
  num_points: 4096
  dataset_folder: /home/ps/cjf/nas/Datasets
  aug_mode: 1
  pin_memory: false
model: 
  name: MinkFPN_GeM
  mink_quantization_size: 0.01
  planes: [32,64,64]
  layers: [1,1,1]
  num_top_down: 1
  conv0_kernel_size: 5
  output_dim: 256
  feature_size: 256
  normalize_embeddings: False
train: 
  num_workers: 4
  batch_size: 32
  batch_size_limit: 256
  batch_expansion_rate: 2
  batch_expansion_th: 0.5
  memory:
    num_pairs: 256
  optimizer: 
    lr: 0.001
    weight_decay: 0.001
    scheduler: 'CosineAnnealingLR'
    # scheduler: 'MultiStepLR'
    scheduler_milestones: [30]
    epochs: 60
    min_lr: 0.00012
  loss: 
    pr:
      name: BatchHardTripletMarginLoss
      margin: 0.2
    incremental:
      # name: 'LwF'
      name: 'StructureAware'
      weight: 110
      margin: 0.0002
      adjust_weight: True 
      gamma: 10
eval:
  batch_size: 256
  thresh_min: 0
  thresh_max: 1
  num_thresholds: 1000
  similarity: euclidean
