debug: false
save_dir: /heyufei1/models/ccl/cjf_results/oxford_mink
data: 
  num_points: 4096
  dataset_folder: /home/ps/cjf/nas/Datasets/benchmark_datasets
  aug_mode: 1
  pin_memory: True
model: 
  # name: logg3d
  # name: PointNetVlad
  name: MinkFPN_GeM
  mink_quantization_size: 0.01
  planes: [32,64,64]
  layers: [1,1,1]
  num_top_down: 1
  conv0_kernel_size: 5
  output_dim: 256
  feature_size: 256
  normalize_embeddings: False
train: 
  num_workers: 4
  batch_size: 32
  batch_size_limit: 256
  batch_expansion_rate: 2

  memory:
    num_pairs: 256
  optimizer: 
    name: 'SGD'
    momentum: 0.9
    lr: 0.03
    weight_decay: 0.001
    scheduler: 'MultiStepLR'
    scheduler_milestones: [120,160]
    epochs: 200
  loss: 
    incremental:
      name: 'KD'
      weight: 1 # KD default 1
      margin: 0.0002
      adjust_weight: True 
      gamma: 10 # default 10
eval:
  batch_size: 32
  thresh_min: 0
  thresh_max: 1
  num_thresholds: 1000
  similarity: euclidean
